apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hub-cluster
  region: us-east-1
  version: "1.34"

iam:
  withOIDC: true

managedNodeGroups:
  - name: hub-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    amiFamily: AmazonLinux2023
