apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-metadata
  namespace: argocd
  labels:
    cloud: azure
    region: southeastasia
    env: production
data:
  name: aks-southeastasia
  server: "https://spoke-aks-spoke-rg-southea-4bec02-zakxp4qu.hcp.southeastasia.azmk8s.io:443"
