apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabase-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XDatabase
  resources:
    - name: rds-instance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            region: us-west-2
            instanceClass: db.t3.micro
            engine: postgres
            engineVersion: "15"
            allocatedStorage: 20
            skipFinalSnapshot: true
            publiclyAccessible: false
            dbName: ordersdb
            username: adminuser
            passwordSecretRef:
              namespace: crossplane-system
              name: rds-password
              key: password
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
