apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabase-gcp
  labels:
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XDatabase
  resources:
    - name: cloudsql-instance
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: DatabaseInstance
        spec:
          forProvider:
            region: europe-west1
            databaseVersion: POSTGRES_15
            settings:
              - tier: db-f1-micro
                diskSize: 20
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.settings[0].diskSize
