apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml
  - providers/providers.yaml
  - providers/runtimeconfig.yaml
  - providers/aws-providerconfig.yaml
  - providers/azure-providerconfig.yaml
  - providers/gcp-providerconfig.yaml
