cert-manager:
  installCRDs: true
  startupapicheck:
    enabled: false

metrics-server:
  enabled: true

keda:
  crds:
    install: false
  operator:
    replicaCount: 1

server:
  persistentVolume:
    enabled: false
  remoteWrite:
    - url: http://ad883df6fcc5d4fa88ffa5ff8696d51f-2061370524.us-east-1.elb.amazonaws.com:19291/api/v1/receive

alertmanager:
  enabled: false
  persistence:
    enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true
