cert-manager:
  installCRDs: true

metrics-server:
  enabled: true

keda:
  crds:
    install: false
  operator:
    replicaCount: 1
prometheus:
  server:
    persistentVolume:
      enabled: false

  alertmanager:
    enabled: false
    persistence:
      enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: true
